mod avatar;
mod manifest;
mod onboarding;

pub use avatar::AvatarAnimation;
pub use avatar::AvatarAnimationFrame;
pub use avatar::AvatarFrameSpec;
pub use avatar::AvatarPackErrorKind;
pub use avatar::AvatarPackValidationError;
pub use avatar::AvatarRenderMode;
pub use avatar::ValidatedAvatarPack;
pub use avatar::validate_avatar_selector;
pub use manifest::AvatarPlacement;
pub use manifest::AvatarSelector;
pub use manifest::CharacterCatalog;
pub use manifest::CharacterManifestV1;
pub use manifest::ConflictKind;
pub use manifest::MatchKind;
pub use manifest::ResolvedCharacter;
pub use manifest::ValidationIssue;
pub use manifest::ValidationIssueCode;
pub use manifest::ValidationReport;
pub use manifest::validate_manifest_path;
pub use manifest::validate_canonical_id;
pub use onboarding::ActivationError;
pub use onboarding::ActivationJournal;
pub use onboarding::ActivationJournalCoordinator;
pub use onboarding::ActivationPhase;
pub use onboarding::CharacterWizardRequestV1;
pub use onboarding::CharacterWizardResultV1;
pub use onboarding::LastActiveStore;
pub use onboarding::CharacterPackageSource;
pub use onboarding::DirectoryPackageSource;
pub use onboarding::WizardOperation;
pub use onboarding::WizardOperationId;
pub use onboarding::WizardOperationReceipt;
pub use onboarding::WizardOutcome;
pub use onboarding::encode_bounded_request;
pub use onboarding::resolve_candidate_path;
pub use onboarding::resolve_wizard_executable;

pub const CHARACTER_SCHEMA_VERSION: u32 = 1;
